import type { Config } from 'tailwindcss'
import tailwindAnimate from 'tailwindcss-animate'
import tailwindcssRadixColors from 'tailwindcss-radix-colors'
import tailwindcssJoin from './lib/tailwindcss-join'

const config: Config = {
  darkMode: ['class'],
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './registry/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        'fg-invert': 'hsl(var(--fg-invert))',
        body: 'hsl(var(--body))',
        button: 'hsl(var(--button))',
        card: {
          DEFAULT: 'hsl(var(--card))',
          fg: 'hsl(var(--card-fg))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          fg: 'hsl(var(--popover-fg))',
        },
        secondary: {
          DEFAULT: 'hsl(var(--secondary))',
          fg: 'hsl(var(--secondary-fg))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          fg: 'hsl(var(--muted-fg))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          light: 'hsl(var(--accent-light))',
          dark: 'hsl(var(--accent-dark))',
          fg: 'hsl(var(--accent-fg))',
        },
        primary: {
          '1': 'hsl(var(--primary-1))',
          '2': 'hsl(var(--primary-2))',
          '3': 'hsl(var(--primary-3))',
          '4': 'hsl(var(--primary-4))',
          '5': 'hsl(var(--primary-5))',
          '6': 'hsl(var(--primary-6))',
          '7': 'hsl(var(--primary-7))',
          '8': 'hsl(var(--primary-8))',
          '9': 'hsl(var(--primary-9))',
          '10': 'hsl(var(--primary-10))',
          '11': 'hsl(var(--primary-11))',
          '12': 'hsl(var(--primary-12))',
          DEFAULT: 'hsl(var(--primary))',
          bg: 'hsl(var(--primary-bg))',
          '1-legacy': 'hsl(var(--primary-1-legacy))',
          '2-legacy': 'hsl(var(--primary-2-legacy))',
          '3-legacy': 'hsl(var(--primary-3-legacy))',
          '5-legacy': 'hsl(var(--primary-5-legacy))',
          '6-legacy': 'hsl(var(--primary-6-legacy))',
          fg: 'hsl(var(--primary-fg))'
        },
        destructive: {
          '1': 'hsl(var(--destructive-1))',
          '2': 'hsl(var(--destructive-2))',
          '3': 'hsl(var(--destructive-3))',
          '4': 'hsl(var(--destructive-4))',
          '5': 'hsl(var(--destructive-5))',
          '6': 'hsl(var(--destructive-6))',
          '7': 'hsl(var(--destructive-7))',
          '8': 'hsl(var(--destructive-8))',
          '9': 'hsl(var(--destructive-9))',
          '10': 'hsl(var(--destructive-10))',
          '11': 'hsl(var(--destructive-11))',
          '12': 'hsl(var(--destructive-12))',
          DEFAULT: 'hsl(var(--destructive))',
          bg: 'hsl(var(--destructive-bg))',
          '1-legacy': 'hsl(var(--destructive-1-legacy))',
          '2-legacy': 'hsl(var(--destructive-2-legacy))',
          '3-legacy': 'hsl(var(--destructive-3-legacy))',
          '5-legacy': 'hsl(var(--destructive-5-legacy))',
          '6-legacy': 'hsl(var(--destructive-6-legacy))',
          fg: 'hsl(var(--destructive-fg))'
        },
        warning: {
          '1': 'hsl(var(--warning-1))',
          '2': 'hsl(var(--warning-2))',
          '3': 'hsl(var(--warning-3))',
          '4': 'hsl(var(--warning-4))',
          '5': 'hsl(var(--warning-5))',
          '6': 'hsl(var(--warning-6))',
          '7': 'hsl(var(--warning-7))',
          '8': 'hsl(var(--warning-8))',
          '9': 'hsl(var(--warning-9))',
          '10': 'hsl(var(--warning-10))',
          '11': 'hsl(var(--warning-11))',
          '12': 'hsl(var(--warning-12))',
          DEFAULT: 'hsl(var(--warning))',
          bg: 'hsl(var(--warning-bg))',
          '1-legacy': 'hsl(var(--warning-1-legacy))',
          '2-legacy': 'hsl(var(--warning-2-legacy))',
          '3-legacy': 'hsl(var(--warning-3-legacy))',
          '5-legacy': 'hsl(var(--warning-5-legacy))',
          '6-legacy': 'hsl(var(--warning-6-legacy))',
          fg: 'hsl(var(--warning-fg))'
        },
        success: {
          '1': 'hsl(var(--success-1))',
          '2': 'hsl(var(--success-2))',
          '3': 'hsl(var(--success-3))',
          '4': 'hsl(var(--success-4))',
          '5': 'hsl(var(--success-5))',
          '6': 'hsl(var(--success-6))',
          '7': 'hsl(var(--success-7))',
          '8': 'hsl(var(--success-8))',
          '9': 'hsl(var(--success-9))',
          '10': 'hsl(var(--success-10))',
          '11': 'hsl(var(--success-11))',
          '12': 'hsl(var(--success-12))',
          DEFAULT: 'hsl(var(--success))',
          bg: 'hsl(var(--success-bg))',
          '1-legacy': 'hsl(var(--success-1-legacy))',
          '2-legacy': 'hsl(var(--success-2-legacy))',
          '3-legacy': 'hsl(var(--success-3-legacy))',
          '5-legacy': 'hsl(var(--success-5-legacy))',
          '6-legacy': 'hsl(var(--success-6-legacy))',
          fg: 'hsl(var(--success-fg))'
        },
        info: {
          '1': 'hsl(var(--info-1))',
          '2': 'hsl(var(--info-2))',
          '3': 'hsl(var(--info-3))',
          '4': 'hsl(var(--info-4))',
          '5': 'hsl(var(--info-5))',
          '6': 'hsl(var(--info-6))',
          '7': 'hsl(var(--info-7))',
          '8': 'hsl(var(--info-8))',
          '9': 'hsl(var(--info-9))',
          '10': 'hsl(var(--info-10))',
          '11': 'hsl(var(--info-11))',
          '12': 'hsl(var(--info-12))',
          DEFAULT: 'hsl(var(--info))',
          bg: 'hsl(var(--info-bg))',
          '1-legacy': 'hsl(var(--info-1-legacy))',
          '2-legacy': 'hsl(var(--info-2-legacy))',
          '3-legacy': 'hsl(var(--info-3-legacy))',
          '5-legacy': 'hsl(var(--info-5-legacy))',
          '6-legacy': 'hsl(var(--info-6-legacy))',
          fg: 'hsl(var(--info-fg))'
        },
        gray: {
          '1': 'hsl(var(--gray-1))',
          '2': 'hsl(var(--gray-2))',
          '3': 'hsl(var(--gray-3))',
          '4': 'hsl(var(--gray-4))',
          '5': 'hsl(var(--gray-5))',
          '6': 'hsl(var(--gray-6))',
          '7': 'hsl(var(--gray-7))',
          '8': 'hsl(var(--gray-8))',
          '9': 'hsl(var(--gray-9))',
          '10': 'hsl(var(--gray-10))',
          '11': 'hsl(var(--gray-11))',
          '12': 'hsl(var(--gray-12))'
        },
        invert: {
          '1': 'hsl(var(--invert-1))',
          '2': 'hsl(var(--invert-2))',
          '3': 'hsl(var(--invert-3))',
        },
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: {
          focus: 'hsl(var(--ring-focus))',
          accent: 'hsl(var(--ring-accent))',
        },
        chart: {
          '1': 'hsl(var(--chart-1))',
          '2': 'hsl(var(--chart-2))',
          '3': 'hsl(var(--chart-3))',
          '4': 'hsl(var(--chart-4))',
          '5': 'hsl(var(--chart-5))',
        },
        segment: {
          DEFAULT: 'hsl(var(--segment))',
          fg: 'hsl(var(--segment-fg))',
          active: {
            DEFAULT: 'hsl(var(--segment-active))',
            fg: 'hsl(var(--segment-active-fg))',
          },
        },
        sidebar: {
          DEFAULT: 'hsl(var(--sidebar-bg))',
          fg: 'hsl(var(--sidebar-fg))',
          primary: 'hsl(var(--sidebar-primary))',
          'primary-fg': 'hsl(var(--sidebar-primary-fg))',
          accent: 'hsl(var(--sidebar-accent))',
          'accent-fg': 'hsl(var(--sidebar-accent-fg))',
          border: 'hsl(var(--sidebar-border))',
          ring: 'hsl(var(--sidebar-ring))',
        },
      },
      borderRadius: {
        DEFAULT: 'var(--radius)',
        xl: 'calc(var(--radius) + 4px)',
        'xl-1': 'calc(var(--radius) + 3px)',
        lg: 'var(--radius)',
        'lg-1': 'calc(var(--radius) - 1px)',
        md: 'calc(var(--radius) - 2px)',
        'md-1': 'calc(var(--radius) - 3px)',
        sm: 'calc(var(--radius) - 4px)',
        'sm-1': 'calc(var(--radius) - 5px)',
        xs: 'calc(var(--radius) - 6px)',
        'xs-1': 'calc(var(--radius) - 7px)',
      },
      keyframes: {
        'accordion-down': {
          from: { height: '0' },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: '0' },
        },
        'collapsible-down': {
          from: { height: '0' },
          to: { height: 'var(--radix-collapsible-content-height)' },
        },
        'collapsible-up': {
          from: { height: 'var(--radix-collapsible-content-height)' },
          to: { height: '0' },
        },
        'spinner-inner': {
          '0%': {
            strokeDasharray: '0 150',
            strokeDashoffset: '0',
          },
          '47.5%': {
            strokeDasharray: '42 150',
            strokeDashoffset: '-16',
          },
          '95%, 100%': {
            strokeDasharray: '42 150',
            strokeDashoffset: '-59',
          },
        },
        'spinner-outer': {
          '100%': {
            transform: 'rotate(360deg)',
          },
        },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
        'collapsible-down': 'collapsible-down 0.2s ease-out',
        'collapsible-up': 'collapsible-up 0.2s ease-out',
        'spinner-inner': 'spinner-inner 1.5s ease-in-out infinite',
        'spinner-outer': 'spinner-outer 2s linear infinite',
      },
    },
  },
  plugins: [
    tailwindAnimate,
    tailwindcssRadixColors,
    tailwindcssJoin,
  ],
}
export default config
